services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./gff:/app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    dns:
      - 8.8.8.8
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    dns:
      - 8.8.8.8

volumes:
  postgres_data: